/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ResultComponent {
    'name': string;
    'url': string;
  }
  interface ResultComponentAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'url'?: string;
  }

  interface SearchComponent {
    'placeholder': string;
  }
  interface SearchComponentAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ResultComponent': Components.ResultComponent;
    'SearchComponent': Components.SearchComponent;
  }

  interface StencilIntrinsicElements {
    'result-component': Components.ResultComponentAttributes;
    'search-component': Components.SearchComponentAttributes;
  }


  interface HTMLResultComponentElement extends Components.ResultComponent, HTMLStencilElement {}
  var HTMLResultComponentElement: {
    prototype: HTMLResultComponentElement;
    new (): HTMLResultComponentElement;
  };

  interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {}
  var HTMLSearchComponentElement: {
    prototype: HTMLSearchComponentElement;
    new (): HTMLSearchComponentElement;
  };

  interface HTMLElementTagNameMap {
    'result-component': HTMLResultComponentElement
    'search-component': HTMLSearchComponentElement
  }

  interface ElementTagNameMap {
    'result-component': HTMLResultComponentElement;
    'search-component': HTMLSearchComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
